syntax = "proto3";

package test;

option go_package = "./test";

import "google/protobuf/descriptor.proto";

extend google.protobuf.EnumValueOptions {
  string info = 54321;
  string description = 54322;
  string measure = 54323;
}

message PersonsEnumType {
  enum SignalType {
    UNDEFINED = 0 [
      (info)="undefined_topic",
      (description) = "someDesc",
      (measure) = "sec"
    ];
    HELL_ONE = 1 [
      (info)="hellone_topic",
      (description) = "someDesc",
      (measure) = "sec"
    ];
    HELL_TWO = 2 [
      (info)="helltwo_topic",
      (description) = "someDesc",
      (measure) = "sec"
    ];
  }
}

message SomeEnumType {
  enum SomeSignalType {
    UNDEFINED = 0 [
      (info)="undefined_type",
      (description) = "someDesc",
      (measure) = "sec"
    ];
    HELLONE = 1 [
      (info)="hellone_type",
      (description) = "someDesc",
      (measure) = "sec"
    ];
    HELLTWO = 2 [
      (info)="helltwo_type",
      (description) = "someDesc",
      (measure) = "sec"
    ];
  }
}