syntax = "proto3";

package test;

option go_package = "./test";

import "google/protobuf/descriptor.proto";

extend google.protobuf.EnumValueOptions {
  string description = 5000;
  string parent_message = 5001;
}

enum Signals {
  SignalUnspecified = 0;
  SignalLat = 701 [
    (parent_message) = "SomeGeo.latitude"
  ];
  SignalLong = 702 [
    (parent_message) = "SomeGeo.longitude"
  ];
  SignalDiff = 805;
}

message SomeGeo {
  optional float latitude = 1;
  optional float longitude = 2;
  optional float altitude = 3;
  optional float some = 4;
}

message SomeGeoPacked {
  float latitude = 1;
  float longitude = 2;
}

message PackedBundle {
  bytes value = 1;
  google.protobuf.DescriptorProto descriptor = 2;
}